---

- hosts: all
  sudo: yes
  tasks:
    - name: Ensure packages are installed
      apt: >-
        pkg="{{ item }}" state=present
      with_items:
        - redis-server
        - git
        - g++
        - libsqlite3-dev
        - openjdk-7-jdk

- hosts: all
  # do as "vagrant" user
  sudo: no
  tasks:
    - name: Ensure that Ruby packages and tools are installed
      script: files/install_ruby_tools.sh 2.1.3

# TODO: run rails generator and rake tasks to set up wrapper app, etc.
